### ISSUE TITLE
Wrong settings if Trainer/Teacher AND Student.

### ISSUE THREAD

**Issue by OZimmermann** [jcrodriguez-dis/moodle-mod_vpl#187]
Hello, thanks for great work :-) 
In some courses I have to be a trainer/teacher and also a student. But then I automatically lose the settings that are otherwise only visible to the trainers, e.g. required files, 

1) correct: only be trainer/teacher: 
<img width="1190" alt="image" src="https://github.com/jcrodriguez-dis/vpl-jail-system/assets/82403411/0277c80f-fd0a-49fb-8209-c8b6bf1ff226">
<img width="283" alt="image" src="https://github.com/jcrodriguez-dis/vpl-jail-system/assets/82403411/f4060173-b494-4458-b9b3-52848a5a4e7a">

2) incorrect: be trainer/teacher AND student
<img width="1222" alt="image" src="https://github.com/jcrodriguez-dis/vpl-jail-system/assets/82403411/9771e8b1-a614-48ae-985d-10a8efb23757">
<img width="205" alt="image" src="https://github.com/jcrodriguez-dis/vpl-jail-system/assets/82403411/65ce5f76-a582-465f-bf69-3c8d38258fe7">

Is it possible for you to change this? I want to see the trainer/teachers settings although being trainer/teacher AND student. 

Thanks a lot, Oliver

**Comment by jcrodriguez-dis** [comment]
Dear Oliver,

Thank you for bringing this issue to my attention. After reviewing the problem, it appears that I was overly cautious in defining the original VPL capabilities, prohibiting students from accessing certain features. The mix of teacher and student capabilities led to the removal of the mod/vpl:manage permission, thus limiting the management of VPL activities with this mix of roles. I've noticed that other standard modules, like the task module, are not as restrictive. I will remove these limitations in the next VPL release.

Best regards,
Juan Carlos.

**Comment by OZimmermann** [comment]
Dear Juan Carlos,
would it be possible to adjust the rights until the next school year?
Then I wouldn't have to manually adjust the settings of the VPL instances of my colleagues with admin rights.

Another enquiry: Could the default settings for "execute" and "debug" be set to true? (see attachment) .

Many thanks for the great work. I have already shown VPL at training courses.
Best regards,
Oliver



Am 12. Apr. 2024, 14:15 +0200 schrieb Zimmermann LvD ***@***.***>:

**Comment by jcrodriguez-dis** [comment]
Dear @OZimmermann,

This issue has been resolved in the latest release of VPL, version 4.2.4. Please note that while the site administrator can modify role capabilities, I think that these changes are not applied automatically during a plugin update. Maybe that the site administrator must manually update/reset the role capabilities after updating the plugin.

**Comment by OZimmermann** [comment]
Dear Juan Carlos, thank you very much for the information. Unfortunately, access with teacher rights and student rights at the same time still does not work.
I am using Moodle 4.2.9 with updated VPL plugin version 4.2.4 2024053112.
As admin, I have removed the rights for vpl:manage from the Trainer group and given them back. However, the problem remains. If I also give the students the rights for vpl:manage, it works, but of course I don't want that.

please help.
Oliver
Am 18. Juli 2024, 17:57 +0200 schrieb jcrodriguez-dis ***@***.***>:

**Comment by jcrodriguez-dis** [comment]
Dear @OZimmermann

I have not been able to reproduce the issue you described. To assist you better, could you please provide detailed steps on how I can replicate the problem, including what the current result is and what you expect to happen?

With the latest VPL release, if you have reset the VPL capabilities permissions, the Capabilities overview in "Site administration -> Users -> Permissions -> Capability overview" for VPL should look like this:

![imagen](https://github.com/user-attachments/assets/ce42eec6-56a7-4008-ba78-75f12f7868de)

Best regards,
Juan Carlos

**Comment by OZimmermann** [comment]
Dear Juan Carlo, I have attached a video showing the issue.
The video also shows that I allow the necessary permissions for trainer ans must allow ppl:manage to students since trainers are ALWAYS students at the same time.
If I remove the vpl:manage permission for students the required accesses to which a trainer should have access are removed.

Perhaps you can tell me in which file of the source code I can look to see whether a teacher can also have the role of student at the same time.

Best regards,
Oliver

https://github.com/user-attachments/assets/3f66da1c-537b-4540-aba0-dab76b4b46f3

**Comment by OZimmermann** [comment]
Hi Juan Carlos, after the last update of Moodle and now that I have created new VPL instances in Moodle, the permissions are working as they should. 
Thanks for everything. 
Oliver
